name "vagrant_main"

depends	"mongodb"
depends "apache2"
depends "apt"
depends "build-essential"
depends "chef_handler"
depends "mysql"
depends "networking_basic"
depends "openssl"
depends "php"
depends "windows"
depends "xdebug"
depends "xml"
depends "phpunit"
depends "composer"